version: '3'

services:
  postgresql:
    image: 'docker.io/postgres:15-alpine'
    environment:
      POSTGRES_DB: similarity
      POSTGRES_USER: similarity
      POSTGRES_PASSWORD: p@ssw0rd
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 200M
